apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: image-intellisense
spec:
  selector:
    app: content
  type: LoadBalancer
  ports:
    - name: content-tcp
      protocol: TCP
      port: 8090
      targetPort: content-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
  namespace: image-intellisense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      restartPolicy: Always
      volumes:
        - name: upload-claim
          persistentVolumeClaim:
            claimName: upload-claim
      containers:
        - name: content
          image: image-intellisense/content-retrival-service
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "0.10"
              memory: 256M
            limits:
              cpu: "0.40"
              memory: 1024M
          volumeMounts:
            - name: upload-claim
              mountPath: "/images"
          ports:
            - name: content-tcp
              containerPort: 8090
          env:
            - name: DOWNLOAD_PATH
              value: "/images"
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
              scheme: HTTP
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 4
            successThreshold: 1
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 2
            initialDelaySeconds: 15
