apiVersion: v1
kind: Service
metadata:
  name: redis-db-service
  namespace: image-intellisense
spec:
  selector:
    app: redis
  ports:
    - name: redis-tcp
      protocol: TCP
      port: 6379
      targetPort: redis-tcp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: image-intellisense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      restartPolicy: Always
      containers:
        - name: redis
          image: image-intellisense/redis-db
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "0.10"
              memory: 256M
            limits:
              cpu: "0.40"
              memory: 1024M
          ports:
            - name: redis-tcp
              containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: redis-tcp
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 5
            successThreshold: 3
